# Type, name and class can be strings like "LGBModel" or can be objects like LGBModel
# Do not worry about data-types, the framework will handle them

methods:
  - type: "AGModelBagExperiment"
    name: "LightGBM_c1_BAG_L1_Reproduced"
    model_cls: "LGBModel"
    model_hyperparameters:
      random_state: 0
      n_estimators: 1000
      learning_rate: 0.05
    num_bag_folds: 8
    time_limit: 3600
    calibrate: true

  - type: "AGModelBagExperiment"
    name: "RealMLP_c2_BAG_L1_TD_v2_SM"
    model_cls: "RealMLPModel"
    model_hyperparameters:
      random_state: 0
      use_early_stopping: false
      use_ls: "auto"
      use_roc_auc_to_stop: true
      bool_to_cat: true
      impute_bool: false
      name_categories: true
      td_s_reg: false
    num_bag_folds: 8
    time_limit: 3600

  # - type: "AGModelBagExperiment"
  #   name: "LightGBM_BAG_L1_Custom"
  #   model_cls: "LGBModel"
  #   model_hyperparameters:
  #     num_boost_round: 100
  #     learning_rate: 0.02
  #     ag_args_fit: {
  #       early_stop: None
  #     }
  #   num_bag_folds: 8
  #   time_limit: 3600

  # - type: "AGModelBagExperiment"
  #   name: "XGBoost_c1_BAG_L1_Reproduced"
  #   model_cls: "XGBoostModel"
  #   model_hyperparameters:
  #     random_state: 0
  #     n_estimators: 1000
  #   num_bag_folds: 8
  #   time_limit: 3600
  #   calibrate: true

  # - type: "Experiment"
  #   name: "LightGBM_Custom"
  #   method_cls: "SimpleLightGBM"
  #   method_kwargs:
  #     hyperparameters:
  #       learning_rate: 0.05
  